//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SloziSliku_56_2018.Properties
{
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\baza;Initial Catalog=SloziSliku;Integrated Security=True")]
        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        //[global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\baza;AttachDbFilename=|DataDirectory|\\SloziSliku.mdf" +
        //    ";Integrated Security=True;Connect Timeout=30")]

        //[global::System.Configuration.DefaultSettingValueAttribute(@"Data Source = (LocalDB)\MSSQLLocalDB;AttachDbFilename="+ 
        //         D:\\Diyajniranje softvera\\New folder\\SloziSliku_56_2018\\SloziSliku_56_2018\\SloziSliku.mdf +";Integrated Security = True; Connect Timeout = 30")]

        [global::System.Configuration.DefaultSettingValueAttribute("Data Source = (LocalDB)\\MSSQLLocalDB;AttachDbFilename=  D:\\Diyajniranje softvera\\New folder\\SloziSliku_56_2018\\SloziSliku_56_2018\\SloziSliku.mdf ;Integrated Security = True; Connect Timeout = 30")]


        public string connection {
            get
            {
                return ((string)(this["connection"]));
            }
            set {
                this["connection"] = value;
            }
        }
    }
}
